<?xml version='1.0'?><!DOCTYPE TEI.2 PUBLIC '-//TEI P4//DTD Main Document Type//EN' 'http://www.tei-c.org/Guidelines/DTD/tei2.dtd' [<!ENTITY % TEI.prose 'INCLUDE'><!ENTITY % TEI.linking 'INCLUDE'><!ENTITY % TEI.figures 'INCLUDE'><!ENTITY % TEI.analysis 'INCLUDE'><!ENTITY % TEI.corpus 'INCLUDE'><!ENTITY % TEI.XML 'INCLUDE'><!NOTATION TEI-XML PUBLIC 'TEI P4' 'http://www.tei-c.org/Guidelines/DTD/tei2.dtd'><!-- internal INL dtd --><!ELEMENT b (#PCDATA)><!ELEMENT l (#PCDATA | b)*><!-- end of internal INL dtd -->]><TEI.2><!--<ENTRY id="i428"><teiHeader><fileDesc><titleStmt><title>Roman van Lancelot</title>
</titleStmt>
<interpGrp type="pubYear_from"><interp value="1300"/></interpGrp>
<interpGrp type="witnessYear_from"><interp value="1300"/></interpGrp>
<interpGrp type="pubYear_to"><interp value="1350"/></interpGrp>
<interpGrp type="witnessYear_to"><interp value="1350"/></interpGrp>
<TITEL>Roman van Lancelot</TITEL>
<author>Onbekend</author>
<AARD>Rijm</AARD>
<BRON nr="K46">'s-Gravenhage, Koninklijke Bibliotheek, 129 A 10</BRON>
<DATUM>1300-1350</DATUM>
<OMVANG>36947 verzen</OMVANG>
<BRON.OPM>Het handschrift staat bekend als de zgn. Haagse Lancelot-codex. Deze bevat in totaal 2+241+2 bladen en per blad 3 kolommen. Het totaal aantal verzen bedraagt 87296. De Roman van Lancelot in de Haagse codex is gedeeltelijk overgeleverd en bevindt zich op fol. 1-99. De codex bevat achtereenvolgens: Boek II: het vervolg van de Roman van Lancelot (fol. 1-99, vs. 1-36947), Roman van Perchevael (fol. 100-115, vs. 36951-42546), Roman van Moriaen (fol. 116-128, vs. 42547-47262); Boek III: Queeste van den Grale (fol. 129-158vc, vs. 1-11160), Wrake van Ragisel (verkorte versie) (fol. 158vc-166, vs. 11161-14580), Roman van den riddere metter mouwen (verkorte versie) (fol. 167-177, vs. 14581-18602), Walewein ende Keye (fol. 178-187, vs. 18603-22270), Lanceloet en het hert met de witte voet (fol. 188-190rb, vs. 22271-23126), Roman van Torec (fol. 190rc-200, vs. 23127-26980); Boek IV: Arturs doet (fol. 201-238, vs. 1-13054). Boek I, met het begin van de Roman van Lancelot, is verloren gegaan.</BRON.OPM>
<EDITIE>W.J.A. Jonckbloet (ed.): Roman van Lancelot, (XIIIe eeuw). Naar het (eenig-bekende) handschrift der Koninklijke Bibliotheek, op gezag van het gouvernement uitgegeven. 's-Gravenhage, 1846-1849. dl. 1, 1-247.</EDITIE>
<STATUS>Kritisch</STATUS>
<BRONMNW>797</BRONMNW>
<BRONMNW>798 (ander handschrift)</BRONMNW>
<EDITIE.OPM>Er is gebruik gemaakt van de gedigitaliseerde versie van Jonckbloets uitgave die tot stand kwam aan de KU Nijmegen. Deze elektronische versie bevat enkele kleine verschillen met de editie van Jonckbloet. Niet overgenomen werden: het trema, het uitroepteken, de clausstreep en het commentaar "(sic)"; voorts springt de tekst nergens in. </EDITIE.OPM>
<BRONNEN>De Roman van Lancelot is gedeeltelijk overgeleverd in de zogenaamde Haagse Lancelot-codex. Verder zijn er van de tekst twee fragmenten overgeleverd, die mogelijk tot hetzelfde handschrift behoord hebben. Van deze twee fragmenten blijft er &eacute;&eacute;n buiten beschouwing ('s-Gravenhage, Koninklijke Bibliotheek, 75 H 58), omdat de tekst overeenkomt met Bk. II, vs. 27338-27733 in de Haagse Lancelot-codex (volgens de uitgave Jonckbloet (1846-1849)). De signaturen van de Haagse Lancelot-codex en het andere fragment, waarvan de tekst wel wordt aangeboden, zijn achtereenvolgens: - <x nr=K46>'s-Gravenhage, Koninklijke Bibliotheek, 129 A 10, fol. 1-99</x>
 - <x nr=K47>Brussel, Koninklijke Bibliotheek, II 115,3 (fragm.)</x>
</BRONNEN>
</fileDesc>
</teiHeader>
--><text>
<l><edition n="1"/><scribe id = "A"/>God, die makere es alre dinc,</l>
<l>Dat nie was of lijf ontfinc,</l>
<l>Die moet mi helpen in derre noet.</l>
<l>Maria, moedermaget goet,</l>
<l n="5">Staet mi bi in allen dingen</l>
<l>So dat ic te poente volbringen</l>
<l>Moete dit boec na sijn recht.</l>
<l>Hier voren hebbic u verplecht</l>
<l>Van vele scoenre avonturen;</l>
<l n="10">Mar wildi vort mit lesen duren</l>
<l>Ghi sult hier horen scone die ieesten</l>
<l>Bede van rouwen ende van feesten,</l>
<l>Van ridderscape groete daet,</l>
<l>Van selsieneheden menich baraet,</l>
<l n="15">Die dese partie hevet in:</l>
<l>Nu hort hier int begin.</l>
<l>Niet lange nadat doet was</l>
<l>Meliagant, als ic voren las,</l>
<l>Des conincs Bandemagus sone,</l>
<l n="20">Daer groet seer was om, na tgone</l>
<l>Voer Artur met geselscapen groet</l>
<l>Jaegen in een foreest van Kameloet,</l>
<l>.Viij. dage na Sinxenen. Daer oec waren</l>
<l>.Xij. gecroende coninge tuwaren,</l>
<l n="25">Die algader uptie ure</l>
<l>Lant hilden vanden coninc Arture.</l>
<l>Hen quamen vele dingen toe,</l>
<l>Dat niet te wonderne en was doe</l>
<l>Bider redenen dat noch doe niet</l>
<l n="30">Des conincs Arturs hof ne sciet,</l>
<l>Dat hi helt in Cornuwaelgen;</l>
<l>Geen edel man sonder faelgen</l>
<l>Ne was noch doe vandaer gesceden.</l>
<l>Die coninginne quam na gereden</l>
<l n="35">Met vrouwen ende met ioncfrouwen,</l>
<l>Diermen daer vele mochte scouwen;</l>
<l>Maer sine hadden doe al dare</l>
<l>Maer .iiij. ridders met hare.</l>
<l>Keye ende Sagramor dese twee</l>
<l n="40">Waeren met hare, ende noch mee</l>
<l>Dodineel die welde, dats drie:</l>
<l>Die vierde, alsict gescreven sie,</l>
<l>Was Lancelot van Lac, die gone</l>
<l>Was conincs Bans van Benewijc sone,</l>
<l n="45">Die vrome ridder was ende waert.</l>
<l>Daer was die sciltknecht in die vaert,</l>
<l>Die enen bracke vorde daer bi,</l>
<l>Ende was der coninginne, die si</l>
<l>Altoes met hare voren dede</l>
<l n="50">Waer si voer, telker stede,</l>
<l>Dore der vrouwen van Lac minne,</l>
<l>Diese gaf der coninginne.</l>
<l>Die coninginne entie vrouwen</l>
<l>Voren na die iachte scouwen,</l>
<l n="55">So dat si omtrent primetijt quamen</l>
<l>Gereden, dat si vernamen</l>
<l>Enen ridder comen te hen wart</l>
<l>Wel gewapent op een part,</l>
<l>Scilt om hals, spere in die hant,</l>
<l n="60">Helm op thoeft. Ende als hi vant</l>
<l>Die coninginne weendi sere.</l>
<l>Die coninginne groette den here,</l>
<l>Ende hi hare dat was clene,</l>
<l>Want hi niet ne mochte van wene</l>
<l n="65">Hare antworden openbaerlike;</l>
<l>Nochtan groette hise hovesscelike.</l>
<l>Ende die coninginne reet vort</l>
<l>Sonder meer te sprekene wort:</l>
<l>Ende doe si dus was verre voren</l>
<l n="70">Sloech hi na vaste met sporen,</l>
<l>Ende reet der coninginne bet nare</l>
<l>Ende sprac al wenende te hare:</l>
<l>"Vrouwe, neemt hier minen pant van al</l>
<l>Dat ic hebbe mesdaen of mesdoen sal</l>
<l n="75">Mijns ondanx." Ende sonder beide</l>
<l>Nam hise biden breidel ende seide:</l>
<l>"Vrouwe, ic va u, ende sonder waen</l>
<l>Ne mogedi mi niet lichte ontgaen."</l>
<l>Ende hi weende emmer toe.</l>
<l n="80">"Ridder, laet staen," seidsi doe.</l>
<l>"Ine [mach], vrouwe," antworde hi.</l>
<l>Doe seide Keye die daer was bi:</l>
<l>"Laet mire vrouwe varen, here,</l>
<l>Of gi sult ontgelden sere."</l>
<l n="85">Hi sprac: "Here Keye, ine laets niet,</l>
<l>En si datmi el ieman verbiet."</l>
<l>Keye trac tswert ende sprac daer nare:</l>
<l>"Ridder, doet uwe hant van hare</l>
<l>Ocht neen ic salse u af slaen."</l>
<l n="90">Die ridder sprac tote Keyen saen:</l>
<l>"Wine sullen onder ons beiden,</l>
<l>Here Keye, niet moegen sceiden</l>
<l>Gine moet ioesteren hier iegen mi."</l>
<l>"Daer mickic clene op," seide hi,</l>
<l n="95">"Gine sult die irste niet wesen,</l>
<l>Ic hebbe geioesteert vor desen."</l>
<l>Si begonsten doe met sporen nopen</l>
<l>Die orse, ende onderlinge loepen</l>
<l>Met groter vart, ende onderstaken</l>
<l n="100">Hem so, dattie scilde braken.</l>
<l>Keye brac sijn spere doe,</l>
<l>Maer die ridder staken soe,</l>
<l>Dat hine droech ter erde</l>
<l>Achterwart van sinen parde.</l>
<l n="105">Alse Sagrimor dat hadde versien</l>
<l><edition n="2"/>Hi reet opten riddre mettien,</l>
<l>Ende die ridder weder te hem wert;</l>
<l>Ende quamen met so [groter] vart,</l>
<l>Dat si hem so onderstaken</l>
<l n="110">Dattie vaste scilde braken,</l>
<l>So dat des ridders scilt spleet</l>
<l>Ende die halsberch scoerde gereet;</l>
<l>Maer hine wart niet gewont,</l>
<l>Ende Sagrimor was tier stont</l>
<l n="115">Gesteken so dat hi ter erde</l>
<l>Vallen moeste vanden perde,</l>
<l>Ende die ridder over hem reet</l>
<l>Metten perde. Also als hi leet</l>
<l>Hets wonder dat hem niet ne brac</l>
<l n="120">Therte dat in sinen buec stac.</l>
<l>Des was die coninginne gram</l>
<l>Als si hare ridders dus vernam,</l>
<l>Datse bi sire manlijchede</l>
<l>Een ridder allene onder dede.</l>
<l n="125">Doe wert erre Dodineel</l>
<l>Om sire gesellen achterdeel.</l>
<l>H[i se]ide: "Dese ridder, sonder waen,</l>
<l>Hevet sine ioeste wel gedaen,</l>
<l>Ic moet oec emmer iegen dien</l>
<l n="130">Joesteren, watter af mach geschien."</l>
<l>Hi hadde liever datmen af stake</l>
<l>Dan hi liete te doene wrake</l>
<l>Dan sinen gesellen na sine macht.</l>
<l>Si porreden beide met groter cracht,</l>
<l n="135">Ende onderreden hen tien tide,</l>
<l>Ende onderstaken hen met nide</l>
<l>So dat hare scilden braken</l>
<l>Vanden steken, die si staken,</l>
<l>Ende haer halsberge niet geduren</l>
<l n="140">Ne mochten sine moesten scuren.</l>
<l>Die ridder bleef in sijn gereide</l>
<l>Maer Doedineel viel upter heide</l>
<l>Vanden perde biden gemoete,</l>
<l>Daerne die ridder stac onsoete.</l>
<l n="145">Om dit was die coninginne</l>
<l>Harde drove in haeren sinne.</l>
<l>Vrouwen ende ioncfrouwen dreven mesbaer.</l>
<l>Si hadden doe om Lanceloete vaer;</l>
<l>Die coningin sprac: Ic bidde u,</l>
<l n="150">Here riddre, dat gi wech vaert nu,</l>
<l>Steecti den vierden af ic sal</l>
<l>Daer af droeven mijn leven al."</l>
<l>Hi seide: "Vrouwe, wats gesciet,</l>
<l>Ine mach henen keren niet</l>
<l n="155">Vore dat ic afgesteken si,</l>
<l>Of ic moet u leiden met mi."</l>
<l>Si sprac: "Ontfoerdi mi, sonder waen,</l>
<l>Ic sal mi van rouwen verslaen;</l>
<l>Ine begere te levene niet</l>
<l n="160">Dan voert meer, wats gesciet,</l>
<l>Langer in en gere maniere,</l>
<l>Werden si afgesteken alle viere."</l>
<l>Die ridder haelde ute metter vart</l>
<l>Om te comene te Lanceloete wart:</l>
<l n="165">Lancelot dede oec des gelike.</l>
<l>Doe quam daer gereden verdelike</l>
<l>Ene quene, die Lanceloete nam</l>
<l>Bi den breidele daer hi quam.</l>
<l>"Hout al stille," sprac die vrouwe,</l>
<l n="170">"Ende quyt u van ure trouwe."</l>
<l>"Wat trouwen?" antworde hi,</l>
<l>"Hebbedi mine trouwe?" "Jayic," sprac si,</l>
<l>"Gi sekert mi, sijt wel bedocht,</l>
<l>Daer gi den roeden ridder socht,</l>
<l n="175">Waer dat icken u wijsde dat gi,</l>
<l>Ende ics vermaende, soud gaen met mi.</l>
<l>Ic vermane u daer af nu:</l>
<l>Coemt met mi ende quitet u."</l>
<l>Lancelot antworde dus der quenen:</l>
<l n="180">"Vrouwe, vordi mi dus henen</l>
<l>Ic ware onteert ende keytive</l>
<l>Tallen dage van minen live,</l>
<l>Na dattie riddre ontbeit na mi."</l>
<l>"Ja," sprac die quenen, "ende ochte hi</l>
<l n="185">U verwint ende vaet ic ne sal dan</l>
<l>Gene macht op u hebben vort an."</l>
<l>Lancelot sprac: "Ic ne sal hier van desen,</l>
<l>Des hoepic, niet verwonnen wesen.</l>
<l>Nu biddic u om Gode, vrouwe,</l>
<l n="190">Ende omme mi van desen rouwe,</l>
<l>Ende mi van scanden te levreerne,</l>
<l>Ghevet mi nv orlof te ioesterne</l>
<l>Jegen den riddre ende respijt,</l>
<l>Ende gi so lange ontbijt."</l>
<l n="195">Si sprac dat daer geen verst en ware,</l>
<l>Maer dat [hi] te hans volgede hare.</l>
<l>Sone daede el niet dore mi?</l>
<l>Sprac hi. Si seide: neensi.</l>
<l>Doe seide hi: "Vaert voren dan,</l>
<l n="200">Ende ic sal u volgen an;</l>
<l>Maer sijt alle seker van desen,</l>
<l>Eer gi sult gereden wesen</l>
<l>Ene bogescote gi sult mi</l>
<l>Doet vinden." Doe sprac si: "Twi?"</l>
<l n="205">Bi sin selven sprac Lansloet:</l>
<l>"Ic hadde liever te sine doet</l>
<l>Dan ic sulke scande soude ontfaen</l>
<l>Alse gi mi wilt doen verstaen."</l>
<l>"Ic sal u laeten," sprac si, "ioesteren</l>
<l n="210">Jegen den ridder, wildi mi sweren</l>
<l>Dat gi mi sult volgen also saen</l>
<l>Alse die ioeste sal sijn gedaen."</l>
<l>"Jaic, vrouwe," antworde hi,</l>
<l>"Op dat ic met mi selven si."</l>
<l n="215">"Ic ne wils anders niet," sprac si doe.</l>
<l>Si was soe out wel daer toe</l>
<l>Van .LXX. iaeren, des geloeft,</l>
<l>Nochtan droech si enen cierkel op thoeft.</l>
<l>Dus begonsten si hen gereiden</l>
<l n="220">Om ioesteren onder hen beiden.</l>
<l>Si staeken onderlinge sulke steken</l>
<l>Dattie scilde moesten breken,</l>
<l>Ende die halsberge scuerden doe:</l>
<l>Die glavyen gingen int vleesch toe.</l>
<l n="225">Die ridder stac Lanceloete tien tiden</l>
<l>Metter glavie doer die siden,</l>
<l>Maer die glavie also liep,</l>
<l>Dattie wonde niet ne was diep;</l>
<l>Ende die glavie brac also</l>
<l n="230">Datter een stuc in die zide bleef doe,</l>
<l>So datter lettel af gebrac</l>
<l>Dat hine ter erden niet ne stac.</l>
<l>Lanceloet die hem gevoelde gewont</l>
<l>Stac den ridder soe tier stont,</l>
<l n="235">Dat hine doerstac tien tiden</l>
<l>Dat tyser bleec ter ander siden,</l>
<l>Ende hi viel ter erden doe.</l>
<l>Die quene quam thant daer toe</l>
<l>Ende sprac te Lanceloete ter stede:</l>
<l n="240">"Nu quijt uwe sekerhede."</l>
<l>Ende eer hi omme mochte gesien</l>
<l>Was si verre gereden in dien,</l>
<l>Ende hi volgede hare tien stonde</l>
<l>Sonder te besiene sine wonde,</l>
<l n="245">Ende sonder orlof te nemen an iemen.</l>
<l>Hi volgede, ende daer na sniemen</l>
<l>Sprac die coninginne Keyen toe:</l>
<l>"Vare nu Lanceloet verre alsoe</l>
<l>Metten trinsone inden lichame</l>
<l n="250">Hi saels hebben sulke mesquame,</l>
<l>Dat hire om sal sterven tuwaren."</l>
<l>Keye sprac: "Ic sal na hem varen,</l>
<l>Nochtan weet ic wel dat hi</l>
<l>Niet weder en sal willen keren dor mi."</l>
<l n="255">Die coninginne sprac: "Volgt hem an,</l>
<l><edition n="3"/>Ende of hijs noet hevet helpt hem dan."</l>
<l>Keye volgede Lanceloete saen.</l>
<l>Als hi ene half mile hadde gegaen</l>
<l>Sach hi dat Lanceloet met groter cracht</l>
<l n="260">In een dal iegen .ij. ridders vacht.</l>
<l>Daer waser .iij. maer Lansloet</l>
<l>Hadde den enen geslegen doet,</l>
<l>Ende die andere .ij. bracht hi soe,</l>
<l>Dat si te voet waeren doe;</l>
<l n="265">Ende Lanceloet was oec te voet,</l>
<l>Si hadden sijn pert geslegen doet.</l>
<l>Doe Keye dit hadde gesien</l>
<l>Doe wonderde hem sere van dien,</l>
<l>Ende seide dat al wel quam</l>
<l n="270">Wat dat Lanceloet ane nam</l>
<l>Te doene, dat hi sekerlike</l>
<l>Geluckich was in dit erderike.</l>
<l>Keye quam tote Lanceloete daer nare</l>
<l>Ende seide: "Mi heeft gesint hare</l>
<l n="275">Mijn vrouwe die coninginne nu,</l>
<l>Om te wetene hoet es met u.</l>
<l>Si waent dat gi nu sijt doet."</l>
<l>"Segt mire vrouwen," sprac Lanceloet,</l>
<l>"Dat ik en hebbe en gene dere,</l>
<l n="280">Ende ic metter ioncfrouwe vere;</l>
<l>Maer doet ten ridder sien, des biddic u,</l>
<l>Daer ic iegen ioesteerde nu,</l>
<l>Die gewont es, ocht genesen mach,</l>
<l>Want hi dinct mi heden dien dach</l>
<l n="285">Een der bester ridder wesen,</l>
<l>Daer ic noit eer iosterde vor desen."</l>
<l>"Wie waren die ridders," sprac Keye thant,</l>
<l>"Daer ic u iegen vechtende vant?"</l>
<l>"Ic ne weet," sprac Lanceloet, "maer si</l>
<l n="290">Bestonden in genen bossche mi.</l>
<l>Ic sl[oech] den irsten doet ter vart,</l>
<l>Dandre twee doden mijn part,</l>
<l>Ende Goddanc ic bens ontgaen,</l>
<l>Sine hebben mi geen arch gedaen."</l>
<l n="295">Keye beette ende woude doen</l>
<l>Ute Lanceloets side trensoen.</l>
<l>"Here ridder, laet gaen," sprac die quene,</l>
<l>"Daer sal noch tavont toe sien, ic wene,</l>
<l>Diere mee af weet dan gi doet.</l>
<l n="300">Keert weder, gine sijt daer toe niet vroet."</l>
<l>Lanceloet wildem setten ter vart:</l>
<l>Keye seide: "Here, neemt mijn part,</l>
<l>Gine zult niet gaen te voet van mi."</l>
<l>"Ic neemt gerne," antworde hi,</l>
<l n="305">"Ende gi sult danne te voet wesen."</l>
<l>Hi antworde: "Swiget van desen,</l>
<l>Ic sal wel gedoen." Lancelot sat</l>
<l>Op Keyes part ende doe bat</l>
<l>Heren Keyen te groetene sine vrouwen,</l>
<l n="310">Ende dat si dede met goeder trouwen</l>
<l>Te dien riddre nemen ware,</l>
<l>Dien hi gewont hadde sware.</l>
<l>Lanceloet volgede der quenen ter vart,</l>
<l>Ende Keye ginc ter coninginne wart,</l>
<l n="315">Ende alsi ende die waren met hare</l>
<l>Van haer comenne worden geware,</l>
<l>Ende saegen dat hi te voet was</l>
<l>Hem allen wonderde sere das.</l>
<l>Sagrimor vor iegen hem ter vart,</l>
<l n="320">Ende vragede hem om sijn part.</l>
<l>Hi seide: "Lanceloet voret en wech daer."</l>
<l>Ende hi seide der coninginne daer naer:</l>
<l>"Vrouwe, Lanceloet groet u bi mi,</l>
<l>Ende bidt u sere dat gi</l>
<l n="325">Ten gewonden riddre neemt ware."</l>
<l>"Hets wel gedaen," sprac si daer nare</l>
<l>Ende Keye wart geware doe</l>
<l>Dat hi ontwapent was; daer toe</l>
<l>Waren hem sine wonden gebonden</l>
<l n="330">Ende bereet, ende lach tien stonden</l>
<l>In ene wel bereide orsbare.</l>
<l>Ende die vrouwe ontboet daer nare</l>
<l>Datmen niemen gewage das,</l>
<l>Wie die gewonde riddre was,</l>
<l n="335">Noch wane hi quam: sine woude niet</l>
<l>Dat daer af niemen wiste iet.</l>
<l>Die coninginne voer na die dinc</l>
<l>Metter baren na den coninc,</l>
<l>Ende die orsbare was bedect</l>
<l n="340">Met dieren samite ende berect,</l>
<l>Ende daer boven geleit cruedt ende gras,</l>
<l>Dattoe versch ende groene was.</l>
<l>Si voeren so verre dat si quamen</l>
<l>Tere fonteinen, die hiet bi namen</l>
<l n="345">Der elfvinnen fonteinen; dat was bidien,</l>
<l>Datmense daer dickent hadde gesien,</l>
<l>Ende oec scone vrouwen; mare</l>
<l>Men mochte niet geweten tware</l>
<l>Daer af dat si hieten elfvinnen:</l>
<l n="350">Die lieden woenden inden bosch binnen.</l>
<l>Doe beetten si ter fonteinen daer.</l>
<l>Die coninginne sprac te Sagrimore daer naer:</l>
<l>"Het daede goet eten nu ter tijt."</l>
<l>"Hets waer, vrouwe," seidi, "hadden wijt."</l>
<l n="355">"Ghi moets ons beiagen," sprac si.</l>
<l>"Ine weet waer soeken," seide hi,</l>
<l>"Sonder te Mathamas hoven:</l>
<l>Hi woent anden bosch hier boven."</l>
<l>"Daer suldi beiagen," sprac si, "cleine,</l>
<l n="360">Ic wane hi in al die werelt gemeine</l>
<l>En genen man en haet mere</l>
<l>Dan den coninc minen here,"</l>
<l>Dodineel spraker toe doe saen:</l>
<l>"Entrouwen, te beter doet daer gaen,</l>
<l n="365">Ende wille daer Sagrimor varen</l>
<l>Ic vare met hem tuwaren;</l>
<l>Mijn vrouwe sal hier na ons biden."</l>
<l>"Ic wilt wel," sprac Sagrimor tien tiden.</l>
<l>Si porreden ende maecten hare vart</l>
<l n="370">Te Mathamas hove wart;</l>
<l>Maer si onthopeden beide doe</l>
<l>Omdat hen mesfiel also</l>
<l>Jegen den riddere onder hen beiden,</l>
<l>Die de coninginne woude wech leiden.</l>
<l n="375">Si quamen in een cleine padekin:</l>
<l>Doe si gereden hadden .i. lettelkin</l>
<l>Worden si geware das,</l>
<l>Dat een ridder, die wel gewapent was,</l>
<l>Vorden inganc van enen pawelgioene</l>
<l n="380">Up een part sat, ende die gone</l>
<l>Leende up sine glavye ende sanc</l>
<l>So clare dat al die bosch clanc.</l>
<l>Sagrimor seide: "Mi dunct des,</l>
<l>Dat dese wel te gemake es."</l>
<l n="385">"Hies wel welt," sprac Dodineel,</l>
<l>"Ende hi gelijcter na een deel."</l>
<l>Doe die riddre geware wart</l>
<l>Gereidde hi hem te ioesteerne ter vart.</l>
<l>"Geselle," sprac Sagrimor, "wi</l>
<l n="390">Moeten ioesteren dunket mi."</l>
<l>Dodineel seide: "Dat si met eeren,</l>
<l>Ic sal vor iegen hem ioesteren."</l>
<l>Sagrimor antworde also houde</l>
<l>Dat hi vore ioesteren woude.</l>
<l n="395">Sagrimor trac ten riddre wart.</l>
<l>Elc trac op andren met groter vart,</l>
<l>So dat si hen so onderstaken</l>
<l>Dat haerre beider glavyen braken.</l>
<l>Mettien quam daer ter steden</l>
<l n="400">Ene ioncfrouw up enen muel gereden.</l>
<l>Alsi den strijt hadde gesien</l>
<l>Quam si te Dodinele na dien.</l>
<l>Diese hovescelike groete daer:</l>
<l>"Goet moet u gescien," sprac si daer naer,</l>
<l n="405">"Ocht gi vanden bloeden ridders niet ne sijt,</l>
<l><edition n="4"/>Die niet ne dorren teneger tijt</l>
<l>Ene ioncfrouwe met hen geleiden."</l>
<l>Hi antworde sonder beiden:</l>
<l>"Ic en ben van dien niet, want hen es</l>
<l n="410">Negene ioncfrouwe, des sijt gewes,</l>
<l>In erderike ine soude hare</l>
<l>Dorren geleiden wart ware."</l>
<l>"Gine sout," antworde si, "bedi</l>
<l>Gine sult niet durren volgen mi</l>
<l n="415">Daer ic u leiden sal." Hi sprac doe:</l>
<l>"Ic sal, al wart ter hellen toe."</l>
<l>Doe voer si dapperlike van daer,</l>
<l>Ende Dodineel volgede haer naer,</l>
<l>Also dat si onder hem beden</l>
<l n="420">Sonder spraken te gader reden.</l>
<l>Nu laten wi dese tale staen,</l>
<l>Ende sullen spreken, sonder waen,</l>
<l>Van Sagrimorre daer wijt lieten ere</l>
<l>Ende vanden riddre, die vochten sere.</l>
<l n="425">Nu maect davonture cont</l>
<l>Dat Sagrimor vacht so lange stont</l>
<l>Jegen den ridder vanden pawelgioene</l>
<l>Dattie riddre bi dien doene</l>
<l>So moede was, dat hi niet mere</l>
<l n="430">Jegen Sagrimorre mochte doen were,</l>
<l>So dat hi inden bosch ontfloe,</l>
<l>Alse die anders en wiste waer toe.</l>
<l>Ende alse Sagrimor dochte</l>
<l>Dat hine herhalen niet ne mochte</l>
<l n="435">Doe liet hi dat volgen staen,</l>
<l>Ende sach om Dodinele saen.</l>
<l>Doe Dodineel daer niet ne was</l>
<l>Wonderde hem sere na das</l>
<l>Waer Dodineel wesen mochte,</l>
<l n="440">So dat hine al omme sochte.</l>
<l>Ende al ne vant hine niet nochtan</l>
<l>Pensedi dat hi soude varen dan</l>
<l>Te Mathamas hove wart.</l>
<l>Ende als hi was in die vart</l>
<l n="445">Quam gereden met groter spoet</l>
<l>Een van Arturs iageren in sijn gemoet,</l>
<l>Die was in sine scoudere tier stont</l>
<l>Ende in sijn hoeft sere gewont</l>
<l>Als hi Sagrimors wert geware</l>
<l n="450">Hi kindene de hant daer nare</l>
<l>Biden wapenen die hi droech,</l>
<l>Ende hi riep op hem genoech</l>
<l>Van also verren als hine sach sere:</l>
<l>"Hebt mijns genaden, lieve here."</l>
<l n="455">Sagrimor sprac te hem: "Waer bi</l>
<l>Vliestu so sere, sech mi?"</l>
<l>"Ic vlie, here, nu ter stont</l>
<l>Dore .ij. ridders, die mi hebben gewont,</l>
<l>Ende mi doeden willen daer toe."</l>
<l n="460">"Waer omme es dat?" sprac Sagrimor doe.</l>
<l>"Om enen brec, here, seiden si,</l>
<l>Die si vonden neven mi.</l>
<l>Om dat ic daer iegen sprac entrouwen</l>
<l>Hebben si mi gewont ende te blouwen."</l>
<l n="465">Sagrimor sprac: "Hebt genen vaer,</l>
<l>Mar leidt mi te hant daer."</l>
<l>Die iagere antworde te desen:</l>
<l>"Here, si sullen hier saen wesen."</l>
<l>Mettien sagen si ende vernamen</l>
<l n="470">Dat gene .ij. ridders op hen quamen.</l>
<l>Sagrimor riep op hen saen:</l>
<l>"Gi heren, laet dien brec staen</l>
<l>Gine voertene niewere hene alsoe,"</l>
<l>Si leverden enen sciltknecht doe</l>
<l n="475">Ende hetenen wech varen [son]der vresen,</l>
<l>Hi soude wel bescudt wesen</l>
<l>Vanden riddere die quam te hen wart;</l>
<l>Ende hi vordene wech ter vart.</l>
<l>Mettien ginc Sagrimor nopen</l>
<l n="480">Sijn ors met sporen ende quam gelopen</l>
<l>Op enen riddre, dien hi gaf</l>
<l>Enen slach dat hem thoeft viel af.</l>
<l>Alse die ander ridder dat sach</l>
<l>Sloech hi op Sagrimore enen slach</l>
<l n="485">Dat hi hem sloech een virendeel</l>
<l>Van sinen scilde, die was geheel.</l>
<l>Doe sloegen Sagrimor so weder,</l>
<l>Dat hi moeste ter erde neder.</l>
<l>Die derde quamer toe daer nare</l>
<l n="490">Ende sloech Sagrimorre so sware,</l>
<l>Dat hi nicken moeste wel herde</l>
<l>Opten hals van sinen perde.</l>
<l>Oec trac hine biden helme soe,</l>
<l>Dat hi[ne] bina ter erden warp doe.</l>
<l n="495">Maer Sagrimor hadde groete cracht,</l>
<l>Hi was vrome ende van groter macht,</l>
<l>Ende gaf hem sulken slach te handen,</l>
<l>Dat hine cloefde toten tanden,</l>
<l>Ende viel saen ter erden doet.</l>
<l n="500">Sagrimor liep met haesten groet</l>
<l>Toten andren ende seide</l>
<l>Hi soudene doet slaen sonder beide</l>
<l>Hine gave hem op ter vart.</l>
<l>Dander gaf hem op sijn zwart,</l>
<l n="505">Ende bat hem genaden mede.</l>
<l>Doe nam hine daer ter stede</l>
<l>Ende seide tote hem: "Gi moet mi</l>
<l>Te hant sekeren dat gi</l>
<l>Den brec weder gevet sonder letten,</l>
<l n="510">Ende dat gi u oec sult setten</l>
<l>Inden iagers genaden altoe."</l>
<l>Hi seide hi wilde doen alsoe:</l>
<l>Hi sach en mochte niet anders wesen.</l>
<l>Ende Sagrimor nam van desen</l>
<l n="515">Des ridders sekerhede, dat hi al</l>
<l>Dat hi hem visiert doen sal.</l>
<l>Daer na stac weder in sijn zwert</l>
<l>Sagrimor ende sat up sijn pert,</l>
<l>Ende quam in enen pat tien stonden,</l>
<l n="520">Daer so vele dorne stonden</l>
<l>Daer hi dore moeste riden al in een,</l>
<l>Dat bloedich worden sijns perts been.</l>
<l>Ende doe hi onder die dorne quam</l>
<l>Wart hi tornich ende gram</l>
<l n="525">Ende vloecte doe alle bede</l>
<l>Die dorne entie bramen mede.</l>
<l>Hi reet vort onlange tiden:</l>
<l>Daer sijn wech begonste widen</l>
<l>Daer sach hi een paeuwelgioen saen</l>
<l n="530">Onder ene eyke gericht staen,</l>
<l>Ende ten ingange van dien</l>
<l>Hevet hi enen leliken aen versien,</l>
<l>Die hem die lelijcste dochte wesen</l>
<l>Dien hi noit sach vor desen.</l>
<l n="535">Die aen hadde in die hant daer</l>
<l>Enen groeten stoc ende swaer.</l>
<l>Die naen bleef daer houdende doe.</l>
<l>Die naen quam daer thant toe</l>
<l>Ende sloech Sagrimors pert thant</l>
<l n="540">Metten stocke, dien hi hadde in die hant,</l>
<l>Vor thoeft. Sagrimor om dat</l>
<l>Was erre, want hi hadde gehat</l>
<l>Quaeden wech, ende seide: "Vlie, lelic quaet."</l>
<l>Ende die naen verhief ende slaet</l>
<l n="545">Metten stocke Sagrimors pert mettien</l>
<l>Vor thoeft dat viel duer sine knien.</l>
<l>Doe was Sagrimor so gram,</l>
<l>Dat hine met beide handen nam,</l>
<l>Dat hine soe ter erden stac,</l>
<l n="550">Dat hi wel na die herte brac.</l>
<l>Hi warpene also ter erde</l>
<l>Ende reet over hem metten perde.</l>
<l>Die naen riep lude hulpe doe.</l>
<l>Doe quamer ene ioncvrouwe toe,</l>
<l n="555">Die scoenste die Sagrimor voren dien</l>
<l><edition n="5"/>Noit met oegen hadde gesien,</l>
<l>Ende sprac tote Sagrimorre tier stede:</l>
<l>"Ay riddre, gine doet gene hoveschede</l>
<l>Dat gi hebt geproeft u cracht</l>
<l n="560">An enen minsche van so cleinre macht;</l>
<l>Ende weet dat wel, dat u van dien</l>
<l>Noch mochte herde wel messcien.</l>
<l>Hadt sijn here gesien, sonder waen,</l>
<l>Gine hadter niet hant an gedaen.</l>
<l n="565">Qualijc moet quaet ridder varen</l>
<l>Waer hi es, sonder sparen."</l>
<l>"Dat moete waer sijn," seide hi,</l>
<l>"Waer bi seggedi dat?" Doe seide si:</l>
<l>"Ic segt bi u; noit en dede, sonder waen,</l>
<l n="570">Vaeliant riddre dat gi hebt gedaen.</l>
<l>Ine sach noit so groete dorperhede</l>
<l>Alse gi hebt gedaen daer mede,</l>
<l>Dat gine dus hebt meshandelt nu.</l>
<l>Hadde hi also grote macht boven u</l>
<l n="575">Alse gi boven hem hebt, sijt seker van desen,</l>
<l>Gine hadt niet so coene gewesen</l>
<l>Dat gijs hadt genomen wrake."</l>
<l>"Segt uwen wille van deser sake,"</l>
<l>Sprac Sagrimor tote der ioncvrouwen,</l>
<l n="580">"Also moete mi God helpen, in goeder trouwen,</l>
<l>Ic hads wrake genomen hadt Lanceloet,</l>
<l>Hadt Walewein geweest, ocht hare genoet.</l>
<l>En belget u niet, des biddic u,</l>
<l>Ic bem gereet te beterne nu."</l>
<l n="585">"De bate ontseggic niet," sprac si.</l>
<l>Sagrimor begonste merken daer bi,</l>
<l>Ende wart geware ende sach na das</l>
<l>Dat si scone ende edel was,</l>
<l>Ende om die scoenheit van hare</l>
<l n="590">Seidi dat hi wel quaet ware</l>
<l>Sciede hi van hare sonder meer,</l>
<l>Hine versochtse van minnen eer.</l>
<l>Die ioncvrouwe ginc ten pawelgioene toe,</l>
<l>Ende hi ginc met hare alsoe.</l>
<l n="595">Doe hi ten pawelgioen quam</l>
<l>Wert hi geware ende vernam</l>
<l>Calogremante gevaen tien stonden,</l>
<l>Die geselle was vander tafelronden,</l>
<l>Ende lach in boyen gespannen daer.</l>
<l n="600">Sagrimor vragede hem daer naer</l>
<l>Wine gevaen hadde ende twi?</l>
<l>"Ic segt u, here," antworde hi,</l>
<l>"Heden vroech maecte sine vart</l>
<l>Mijn here die coninc te bossche wart</l>
<l n="605">Om dat hire in iaegen soude,</l>
<l>Ende ic ne porrede also houde</l>
<l>Alse mijn here die coninc dede,</l>
<l>Ende ic quam allene hier ter stede,</l>
<l>Daer ic dese ioncvrouwe doe vant,</l>
<l n="610">Ende soe hadde in hare hant</l>
<l>Enen yvoren horen ende dare</l>
<l>Vragede si och ic so coene ware</l>
<l>Dat ic den horen blasen dorste.</l>
<l>Ic seide: iay ic, ende sonder vorste</l>
<l n="615">Gaf so mi den horen in die hant,</l>
<l>Ende ic bliesene sere thant.</l>
<l>.IJ. gewapende ridders quamen</l>
<l>Cortelike ende namen</l>
<l>Mi, die wel macht hadden das,</l>
<l n="620">Want ic ongewapent was,</l>
<l>Ende leiden mi, alse gi siet, ter stede."</l>
<l>Sagrimor seide dat was dorperhede,</l>
<l>"Ende waendic dat iemen comen soude,</l>
<l>Ic soude den horen blasen houde."</l>
<l n="625">Dander sprac: "Si comen cortelike</l>
<l>Blasedi den horen, sekerlike."</l>
<l>Hi seide: "Dat sal ic sciere sien."</l>
<l>Ende hi nam den horen mettien</l>
<l>Ende deden luden also sere</l>
<l n="630">Alse hi mochte nembermere.</l>
<l>Doe sach hi onlange daer naer</l>
<l>Enen ridder comen daer</l>
<l>Met wapenen al bloet roet,</l>
<l>Ende maecte geruchte groet:</l>
<l n="635">"Entrouwen, ridder, so wee u,</l>
<l>Dat gi den horen blieset nu."</l>
<l>Sagrimor sach dat wesen moeste</l>
<l>Ende gereedde hem ter ioeste,</l>
<l>Ende dander dede tselve doe;</l>
<l n="640">Dus onderreden si hen also,</l>
<l>Dat elc andren stac ter erde,</l>
<l>Ende die lichame onder die perde.</l>
<l>Ende die riddre irst upstoet,</l>
<l>Die vrome was ende goet,</l>
<l n="645">Ende trac sijn zwert uten scoe.</l>
<l>Dat selve dede Sagrimor doe</l>
<l>Ende elc liep andren op tier tijt</l>
<l>So dat lange duerde die strijt.</l>